= Dokumentation Linux Essentials
:toc:

== Hilfe auf der Kommandozeile

* Option `<kommanod> --help`
* Manpages `man <kommando>`: gibt es in der Regel nur für _extern_ realisierte Kommandos, nicht für _Builtins_ (z.B. `cd`, `export`, `alias` usw.)
* `help <builtin>` zeigt die Hifle Seite für Builtins (in die Shell eingebaute Kommandos) an
* `help` Liste aller Builtins
* `type <kommanod>` zeigt die Art eines Kommandos an: extern, Builtin, Alias etc.
* Zusatzinfo: Info System: `info <kommando>` zeigt die Info-Seite eines Kommandos an. Info Seiten sind noch ausführlicher als die Manpages, gibt es aber nicht für alle Kommandos, muss mit `apt install info` installiert werden

== Autocompletion

Mit der TAB-Taste können Pfade, Kommandos, Optionen usw. automatisch vervollständigt werden. Gibt es mehrere Möglichkeiten zur Vervollständigung, kann man zweimal die TAB-Taste drücken und erhält eine Übersicht über die verschiedenen Möglichkeiten.

== Sonderzeichen und Escaping

* In der BASH gibt es bestimmte Sonderzeichen, welche nicht als reguläre Satzzeichen interpretiert werden, sonder eine Sonderbedeutung haben.
* Eins der wichtigsten Sonderzeichen ist das Leerzeichen/Space, dies ist das *Trennzeichen*, hiermit erkennt die Shell z.B. was eine Kommando ist, was eine Option, was ein Argument usw.
* Wollen wir ein Sonderzeichen als reguläres Satzzeichen darstellen ohne Sonderbedeutung, so müssen wir dieses Zeichen _maskieren_ bzw. _escapen_:
* die doppelten Anführungszeichen `"` escapen alle Sonderzeichen bis auf das `$` (Substitution)
* die einfachen Sonderzeichen `'` escapen sämtliche Sonderzeichen
* der Backslash `\` maskiert das direkt darauffolgende Zeichen
* einige Sonderzeichen: 
** `<kommanod1> ; <kommando2>`: beide Kommandos werden nacheinander ausgeführt, unabhängig, ob sie erfolgreich waren oder nicht 
** `<kommando1> && <kommando2>`: `<kommando2>` wird nur dann ausgeführt, wenn `<kommando1>` *erfolgreich ausgeführt* werden konnte
** `<kommando1> || <kommando2>`: `<kommando2>` wird nur dann ausgeführt, wenn `<kommando1>` *nicht erfolgreich ausgeführt* werden konnte
** `~`: Abkürzung für das Heimatverzeichnis des aktuellen Benutzers
** `$`: Substitution/Ersetzung, z.B.: `$var` `$(kommando)` `$(( berechnung ))`
** `#`: Leitet einen Kommentar ein
** `*`: Globbing Character (Asterisk) - steht für ein beliebiges Zeichen, dass beliebig oft vorkommen darf (auch kein Mal)
** `?`: Globbing Character - steht für ein beliebiges Zeichen, dass exakt einaml vorkommt

== Subshells

Eine Shell, die innerhalb einer anderen Shell geöffnet wird. Passiert relativ oft, ohne dass wir es direkt merken, z.B. bei der Kommandosubstitution, beim Aufruf von Funktionen in Skripten usw. Eine Subshell ist abhängig von der Elternshell. Wird die Elternshell geschlossen, werden gleichzeitig auch alle Subshells geschlossen.

== Variablen

* es gibt zwei Arten von Variablen: 
** *Shellvariablen*: sind nur in der aktuellen Shell gültig
** *Umgebungsvariablen*: sind in allen Shells gültig (werden komplett in Großbuchstaben geschrieben [Konvention]), müssen in bestimmten Dateien konfiguriert werden (z.B. `~/.bashrc`, `~/.profile` etc.)
* mit dem Kommado `export` kann eine Shellvariable auch in Subshells verfügbar gemacht werden

== Arithmetische Operationen / Rechnen in der Shell

* Möchte man in der Shell (mit Variablen) rechnen, kann dies auf zwei Weisen erfolgen:

----
$(( ausdruck ))

summe = $(( zahl1 + zahl2))
----

oder:

----
let summe = zahl1 + zahl2
----

Hilfe dazu findet sich in der Manpage der BASH (Suche z.B. nach _arithmetic_ in der englischen Version)

== History

Jedes Kommando wird in der History der Shell gespeichert. Bei der BASH ist es z.B. die Datei `~/.bash_history`. Mit dem Kommando `history` kann eine Liste dieser Kommandos angezeigt werden. Jedes Kommando hat einen Index `<index>`. 

Ein bestimmtes Kommando kann folgendermaßen erneut aufgerufen werden:

 !<index>

Ansonsten können mit den Cursor (Pfeil nach oben) oder mittels STRG+P die zuletzt eingegebenen Kommandos aufgerufen werden.

Andere nützliche History-Shortcuts:

* `!!` das komplette zuletzt eingegebene Kommando (z.B. `sudo !!` um das letzte Kommando erneut mit Root-Rechten auszuführen)
* `!?` das letzte Argument des zuletzt ausgeführten Kommandos:

----
ls -l /some/folder/somewhere/in/path
chown -R tux:tux !$
----

== Brace Expansion

* `touch file_{001..100}.txt` erstellt 100 Dateien mit den Namen `file_001.txt` bis `file_100.txt`
* `ls *.{txt,pdf}` zeigt alle `txt` und `pdf` Dateien an

== Konfigurationsdateien

* Systemweite Konfigurationsdateien: liegen immer unter `/etc`, sind für alle Benutzer gültig (z.B. `/etc/bash.bashrc`)
* Benutzerspezifische Konfigurationsdateien: liegen immer im Heimatverzeichnis des Benutzers, beginnen immer mit einem Punkt (`.`) oder liegen in einem Verzeichnis, das mit einem Punkt beginnt (z.B. `~/.bashrc`, `~/.config/htop`)
* Einträge in den benutzerspezifischen Konfigurationsdateien überschreiben ggf. Einträge aus der systemweiten
* So können Bentzer selbst gewisse Einstellungen vorhnehmen ohne Root-Rechte haben zu müssen, z.B. Aliase erstellen, die BASH konfigurieren...

== Textströme 

== UNIX-Philosophie

1. Schreibe Programme so, dass sie *eine* Aufgabe erledigen, und diese gut machen
2. Schreibe Programme so, dass sie zusammenarbeiten
3. Schreibe Programme so, dass sie Textströme verarbeiten, denn Text ist eine universelle Schnittstelle

== Standardkanäle 

- Standardeingabekanal - `stdin` - Kanalnr. 0
- Standardausgabekanal - `stdout` - Kanalnr. 1
- Standardfehlerkanal - `stderr` - Kanalnr. 2

== Redirect

Mit einem Redirect kann ein Datenstrom in eine *Datei* umgeleitet werden.

- `>` Mit einem _einfachen_ Redirect wird der Standardausgabekanal oder der Standardfehlerkanal in eine Datei umgeleitet. Die Datei muss vorher nicht existiert haben, sie wird ggf. erzeugt. Eine bereits bestehende Datei wird zuerst geleert/der Inhalt gelöscht und anschließend mit dem Inhalt des Datenstroms beschrieben.

 ls /etc 1> ausgabe_ls.txt     # stdout(1) in datei
 ls /etc > ausgabe_ls.txt     # stdout(1) in datei

 ls /gibtsnicht 2> fehler_ls.txt     # stderr(2) in datei

- `>>` Mit einem _doppelten_ (anhängenden) Redirect wird der Inhalt des Datenstroms (`stdout` oder `stderr`) an eine bereits bestehende Datei angehängt. Eine nicht existierende Datei würde erzeugt werden.
- `&>` So werden sowohl `stdout` als auch `stderr` in eine Datei umgeleitet

 ls /etc /gibtsnicht &> ausgabe_und_fehler.txt

`sterr` wird in `stdout` umgeleteitet und dann `stdout` in datei
das `&1` ist nötig, damit der Shell klar ist, dass der Kanal 1 gemeint ist
ansonsten würde die Datei `1` erstellt werden

 ls /etc /gibtsnicht > ausgabe_und_fehler.txt 2>&1    

- `<` Mit dem umgedrehten Redirect kann der Inhalt einer Datei an den Eingabekanal eines Kommandos geleitet werden

 mail -s Mail_Subject empfaenger@mail.example < mailinhalt.txt

== Pipe

Mit der Pipe `|` wird der Ausgabekanal eines Kommandos an den Eingabekanal eines weiteren Kommandos umgeleitet.

- `<Kommando1> | <kommando2>`

 ls -l /etc | less
 grep alias ~/.bashrc | grep -v `#`

== Filterkommandos

Wir nutzen Filterkommandos um aus einem Textstrom den Inhalt zu herauszufiltern, den wir haben wollen 

=== grep

Alle Zeilen anzeigen, die das Pattern `alias` enthalten. Es wird immer die gesamte Zeile ausgegeben in der das Pattern vorkommt.

 grep 'alias' ~/.bashrc

Gesamten Inhalt der Datei `~/.bashrc` anzeigen, Kommentarzeilen *nicht* mit ausgeben

 grep -v `#` ~/.bashrc 

- `grep -i <pattern>`: Gross- und Kleinschreibung von `<pattern>` ist egal
- `grep -n <pattern>`: Anzeige der Zeilennummer, in der `<pattern>` gefunden wurde
- `grep -r <pattern> dir/`: Rekursive Suche, so kann über alle Dateien in einem Verzeichnis _gegrept_ werden
- `grep -v <pattern>`: _inVert match_: Ausgabe wird _invertiert_, also nur die Zeilen ausgegeben, in denen `<pattern>` *nicht* vorkommt
- `grep -c <pattern>`: gibt nicht die Zeilen aus, sondern nur die Anzahl der Zeilen in denen `<pattern>` vorkommt

=== cut

Mit `cut` können wir Spalten/Felder/_Fields_ aus tabellarisch aufgebauten Dateien _ausschneiden_ bzw. filtern. Die wichtigen Optionen für `cut` sind `-d` zur Angabe des Trennzeichens (_Delimiter_) und `-f` zur Angabe der Spalte (_Field_). Bsp.:

Ausschließlich die Login-Namen anzeigen lassen:

 cut -d: -f1 /etc/passwd

=== weitere Filterkommandos

- `tr`: übersetzt ein Zeichen in einem Textstrom (es können keine Dateien als Argument übergeben werden) in ein anderes/löscht dieses etc... 

 tr a A < datei.txt  # wandelt jedes kleine a in ein grosses A um

- `wc`: gibt die Anzahl der Zeilen, Wörter und Bytes einer Datei an 

 wc -l /etc/passwd`  # Anzahl Zeilen der Datei /etc/passwd

== Nach Dateien suchen

=== locate

Die Suche mit `locate` ist im Vergleich zu `find` sehr schnell, da `locate` eine Datenbank zur Suche nutzt bzw. alle Dateien auf dem System vorher mit dem Tool `updatedb` durchsucht und in dieser Datenbank indiziert werden.

`updatedb` wird in der Regel einmal pro Tag automatisch durch `cron` ausgeführt. 

Dadurch ist die Suche sehr schnell, neu erstellte Dateien werden aber unter Umständen nicht gefunden. In dem Fall kann `updatedb` auch manuell mit Root Rechten ausgeführt werden.

Alle README Dateien im gesamten System finden:

 locate README

Alle Dateien, die `tar` im Namen haben finden:

 locate tar

Alle Dateien, die auf `tar` enden finden:

 locate "*.tar"

Die Suche mit `locate` ist schnell aber nicht besonders fein einstellbar.

=== find

- Suche nach Dateien, Verzeichnissen etc. auf Dateisystemebene
- die Suche kann sehr fein eingestellt werden
- es kann z.B. nach folgenden Kriterien gesucht werden:
  - Dateien
  - Verzeichnisse
  - Benutzer
  - Berechtigungen
  - Alter/Zugriffszeit
  - Grösse
  - etc.
- Optionen werden in der Langschreibweise mit nur einem einzelnen Minuszeichen angegeben (UNIX Syntax)
- es können beliebig viele Tests kombiniert werden um die Suche zu verfeinern:

Das foldende Kommando sucht im gesamten Dateisystem nach allen regulären Dateien mit der Endung `.jpg` auf die vor mehr als 5 Minuten zugegriffen wurde:

 find / -name "*.jpg" -type f -amin +5

- mit der Option `-exec` können Kommandos auf die einzelnen Suchergebnisse angewandt werden. Folgendes Kommando löscht alle regulären Dateien, die grösser als 50G sind und dem Benutzer `tux` gehören:

 find / -type f -size +50G -user tux -exec rm {} \; 

Alle regulären Dateien löschen, die grösser als 50G sind und dem Benutzer `tux` gehören:

 find / -type f -size +50G -user tux -delete

=== xargs

Die Ausführung von Kommandos über `-exec` kann unter Umständen recht lange dauern, da `find` für jedes Suchergebniss einen einzelnen Prozess startet.

Mit dem  Kommando `xargs` kann diese Ausführung beschleunigt werden, da `xargs` mehrere Suchergebnisse in einem einzelnen Prozess ausführen kann. Bei der Kombination mit `find` muss hier aber auf etwas geachtet werden. 

Enthält der Dateiname Leerzeichen, würde `xargs` dies als ein Trennzeichen betrachten und somit versuchen ein Kommando nur auf einen Teil des Dateinamens anzuwenden, was natürlich zu einem Fehler führt. Um dies zu umgehen, sorgt man dafür, das `find` Leerzeichen durch ein _Nullbyte_ ersetzt (über die Option `-print0`). Nun muss man aber auch `xargs` darüber unterrichten, d.h. zusätzlich muss `xargs` die Option `-0` übergeben werden:

 find / -type f -size +50G -user tux -print0 | xargs -0 rm 

== Prozesse

Ein Prozess ist ein sich in der Auführung befindliches Programm. Ein Programm resultiert immer in mindestens einem Prozess. Prozesse laufen jeweils in einem von anderen unabhängigen "Resourcenraum", haben eine eigene _PID_, kennen nur die _PID_ des Prozesses, von dem sie gestartet wurden (Elternprozess). Prozesse können mit dem Kommando `kill` über _Signale_ beeinflusst werden.

Wird der Elternprozess beendet, so werden (in der Regel) gleichzeitig alle Kindprozesse mit beendet.

Auf der Shell kann immer nur ein einzelner Prozess im _Vordergrund_ ausgeführt werden. Prozesse können mit der Tastenkomnination `STRG+Z` angehalten und in den Hintergrund geschickt werden. Mit dem Kommando `bg` kann dieser Prozess dann im Hintergund fortgesetzt werden, `fg` holt den Prozess in den Vordergrund zurück. 

Wir können einen Prozess beim Start aber auch direkt in den Hintergrund schicken und starten (duch Anhängen eines `&`):

 kommando &

- `ps -aux`: Anzeige aller laufende Prozessez
- `ps -ef`: auch Anzeige aller laufenden Prozesse
- `ps --forest`: Prozesshirarchie (Baumstruktur) anzeigen
- `jobs`: Anzeigen der Hintergrundprozesse
- `fg`: letzten/aktuellen/default Job in den Vordergrund holen
- `fg %<jobnummer>`: Job mit Jobnummer `<jobnummer>` in den Vordergrund holen
- `bg`: Hintergrundprozess fortsetzen
- `bg %<jobnummer>`: Hintergrundprozess mit Jobnummer `<jobnummer>` in fortsetzen

== kill

`kill` sendet Signale an Prozesse. Es muss die PID des Prozesses angegeben werden, Prozessname funktioniert nicht.

- `kill -s <signal> <PID>`: sendet <signal> an den Prozess mit der PID <PID>
- `kill -<signal> <PID>`: sendet <signal> an Prozess mit der PID <PID>

Die PID eines Prozesses kann auf mehrere Arten ermittelt werden:

 ps -ef | grep <prozessname>
 pgrep <prozessname>
 ...

=== einige wichtige Signale

- `SIGTERM` (15): Standard, falls kein bestimmtes Signal angegeben wird. Sendet eine "freundliche" Aufforderung an den Prozess, sich doch bitte zu beenden. Im Prozess selbst ist festgelegt, wie er sich beendet, z.B. werden noch gewisse Aufräumarbeiten durchgeführt etc.
- `SIGINT` (2): sendet eine etwas deutlichere Aufforderung an den Prozess, sich zu beenden, wird bei der Tastenkomnination `STRG+C` (_Cancel_) gesendet
- `SIGKILL` (9): rabiateste Methode, Signal wird nicht an den Prozess, sondern direkt an den Scheduler gesendet, der daraufhin den entsprechenden Prozess aus seiner Liste löscht, der Prozess somit keine CPU Zeit mehr zur Verfügung gestellt bekommt und somit zwangsläufig beendet wird.
- `SIGSTOP` (19): hält Prozess an und schickt ihn in den Hintergrund (`STRG+Z`)
- `SIGCONT` (18): startet angehaltene Prozesse

=== pkill und killall

- `pkill`: analog zu oben, `pkill` erwartet aber den Namen bzw. einen Teil des Namens eines Prozesses anstatt der PID. Falls mehere Prozesse auf den Namen passen, wird das Signal an *alle* diese Prozesse gesendet.
- `killall` auf neueren Distributionen nicht mehr vorhanden, ähnliches Verhalten wie `pkill`

== Dateisystembaum unter Linux

Filesystem Hierarchy Standard - FHS: Eine Empfehlung an alle Distributionen, wie der Dateisystembaum unter UNIX/Linux aufgebaut sein sollte.

- `/bin`: common executables available for everyone, `ex. cp rm ls`
- `/boot`: kernel and boot configuration, initial ramdisk, kernel image
- `/dev`: files which point to both physical and pseudo devices, populated by `udev`
- `/etc`: systemwide configuration files
- `/home`: non-root user home directories
- `/lib`: library files used by the system, include `.so` files and others
- `/lib32`: library files used by the system, include `.so` files and others
- `/lib64`: library files used by the system, include `.so` files and others
- `/lost+found`: saved files due to failure, not relevant for users, just for the system
- `/media`: auto-mounting place for certain external devices on some distros
- `/mnt`: place to mount various file systems
- `/opt`: various software, not installed by package manager
- `/proc`: virtual filesystem (`procfs`) for resources, processes, and more, only in memory, not actual files on hard disk
- `/root`: root user home directory
- `/sbin`: similar to `/bin`, but for system administrators, ex. `fdisk`
- `/tmp`: temporary file storage, wiped out after reboot
- `/usr`: user programs, library files, docs, etc.
- `/var`: variable files for various purposes, ex. logs, tz data, files for webserver (debian)
- `/vmlinuz`: boot/vmlinuz-4.15.0-43-generic: compressed linux kernel 

=== weitere wichtige Verzeichnisse (nicht Bestandteil des FHS)

- `/sys`: virtual filesystem (`sysfs`), extension to `/proc`
- `/run`: virtual filesystem, was under `/var/run` (symlinked) before, applications can store data needed to operate, e.g. `.lock` files

== Benutzer und Gruppen

Es gibt zwei Arten von Benutzern:
* Systembenutzer/Pseudobenutzer
* Reale Benutzer

=== Dateien der Benutzerverwaltung

* `/etc/passwd`: Liste aller Benutzer auf dem System, tabellarischer Aufbau, Manpage `man 5 passwd`, von allen lesbar
* `/etc/shadow`: Passwörter der Benutzer, gesaltet und gehasht, Ablaufdaten der Passwörter
* `/etc/group`: Liste aller Gruppen und deren Mitglieder
* `/etc/gshadow`: Passwörter für Gruppen, wird eigentlich nicht verwendet

=== Benutzer anlegen

 useradd karl
  
Obiges Kommando erzeugt den Benutzer `karl`, es wird jedoch kein Heimatverzeichnis erstellt und die Shell ist die `/bin/sh`

Mit folgendem Kommando wird der Benutzer `tux` mit eigenem Heimatverzeichnis und darin enthaltener Standarddateien (Kopie von `/etc/skel`) erzeugt, im Kommentarfeld der Name `Tux Tuxedo` und der BASH als Login Shell:

 useradd -m -c 'Tux Tuxedo' -s /bin/bash tux

Anschließend muss mit dem Kommando `passwd tux` noch ein Passwort für `tux` erstellt werden.

Das interaktive Kommando `adduser` unter Debian ist ein Wrapper um `useradd`, welches zusätzlich ein Passswort erstellt.

=== Benutzer ändern

Mit dem Kommando `usermod` können Eigenschaften von Benutzern geändert werden. Die Optionen sind sehr ähnlich zu `useradd`.

=== Gruppen anlegen

Gruppe `gfn` erzeugen:

 groupadd gfn

Benutzer `tux` der Gruppe `gfn` hinzufügen:

 usermod -aG gfn tux

Wichtig ist hier das `-a`, ansonsten werden alle anderen Gruppenzugehörigkeiten von `tux` gelöscht.

Gruppenzugehörigkeiten werden erst aktiv, wenn sich der Benutzer einmal komplett vom System ab- und wieder angemeldet hat.

=== Benutzer wechseln

`su tux`: Wechselt in den Benutzeraccount von `tux`, Umgegung (env, Variablen etc.) werden teilweise neu gesetzt. 
`su - tux`: wie oben, es werden aber alle Umgebungsvariablen neu gesetzt ("echte" Login Shell)
`su -l tux`: wie oben
`su --login tux`: wie oben

=== Besitzer ändern

 chown user <datei>

=== Gruppe ändern

 chgrp group <datei>

 chown :group <datei>

=== Besitzer und Gruppe ändern

 chown user:group <datei>

== Dateibereichtungen

 r : read 
 w : write
 x : execute

 User Group Others
 rw-  r--   r--

== Berechtigungen setzen

=== Symbolische Rechtevergabe

 chmod g+w <datei>   # Schreibrecht für Gruppe hinzufügen

 chmod u-w <datei>   # Schreibrecht für User entziehen

 chmod go-rx <datei>   # Schreibrecht und Ausführungsrecht für Others und Gruppe entziehen

 chmod u=rwx <datei>  # alle Rechte für Owner setzen

=== Oktale/Numerische Rechtevergabe

 r : read     4
 w : write    2
 x : execute  1

       ugo
 chmod 220 <datei>  u=w,g=w
 chmod 620 <datei>  u=rw,g=w


 Okt.   Bin.

 1      001
 2      010
 4      100 

  7  6  4
 111110100
 rwxrw-r--

=== Standardberechtigungen

* auf Datei: 644
* auf Verzeichnis: 755

=== Sonderbits

==== SUID Bit 

Auf eine ausführbare Binärdatei gesetzt, bewirkt das SUID-Bit, dass die Datei mit den Berechtigungen des Besitzers (und nicht den Berechtigungen des aufrufenden Benutzers) ausgeführt wird.

Beispiel:

 /usr/bin/passwd

==== SGID Bit 

Auf eine ausführbare Binärdatei ähnlich wie das SUID-Bit, nur dass die Datei mit den Berechtigungen der Gruppe ausgeführt wird.

Auf ein Verzeichnis angewendet, sorgt das SGID-Bit dafür, dass darin neu erstellte Dateien der Gruppe des Verzeichnisses zugeordnet werden, nicht der initialien Gruppe des Benutzers, der die Datei erstellt.

Beispiel:

 /var/mail

==== Sticky Bit

Auf ein Verzeichnis gesetzt, sorgt es dafür, dass nur der Besitzer einer Datei diese ändern oder löschen darf.

Beispiel:

 /tmp


